# Generated by Django 5.1.2 on 2024-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_AR',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_AR',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_AR',
        ),
        migrations.AddField(
            model_name='category',
            name='name_EN',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_EN',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_EN',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
