# Generated by Django 5.1.2 on 2024-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_category_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(max_length=100)),
                ('name_AR', models.CharField(max_length=100)),
                ('description_EN', models.TextField()),
                ('description_AR', models.TextField()),
            ],
        ),
    ]
