# Generated by Django 5.1.2 on 2024-11-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(default='', upload_to='Projects/'),
            preserve_default=False,
        ),
    ]
