# Generated by Django 5.1.2 on 2024-12-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_excelupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(default='', upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
            preserve_default=False,
        ),
    ]
