# Generated by Django 5.1.2 on 2024-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_excelupload_product_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('featured', 'Featured')], default='new', max_length=20),
        ),
    ]
